before:
  hooks:
    - go vet ./...
    - go test ./...
    - go build
builds:
  -
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  -
    dockerfile: Dockerfile
    image_templates:
    - zetoph/kubernetes-replicator:latest
    - zetoph/kubernetes-replicator:stable
    - zetoph/kubernetes-replicator:{{ .Tag }}
    - zetoph/kubernetes-replicator:{{ .Tag }}-go{{ .Env.GO_VERSION }}
    binaries:
      - kubernetes-replicator
    goos: linux
    goarch: amd64
    goarm: ''
  -
    dockerfile: Dockerfile
    image_templates:
    - zetoph/kubernetes-replicator-arm64:latest
    - zetoph/kubernetes-replicator-arm64:stable
    - zetoph/kubernetes-replicator-arm64:{{ .Tag }}
    - zetoph/kubernetes-replicator-arm64:{{ .Tag }}-go{{ .Env.GO_VERSION }}
    binaries:
      - kubernetes-replicator
    goos: linux
    goarch: arm64
    goarm: ''
  -
    dockerfile: Dockerfile
    image_templates:
    - zetoph/kubernetes-replicator-armv5:latest
    - zetoph/kubernetes-replicator-armv5:stable
    - zetoph/kubernetes-replicator-armv5:{{ .Tag }}
    - zetoph/kubernetes-replicator-armv5:{{ .Tag }}-go{{ .Env.GO_VERSION }}
    binaries:
      - kubernetes-replicator
    goos: linux
    goarch: arm
    goarm: '5'
  -
    dockerfile: Dockerfile
    image_templates:
    - zetoph/kubernetes-replicator-armv6:latest
    - zetoph/kubernetes-replicator-armv6:stable
    - zetoph/kubernetes-replicator-armv6:{{ .Tag }}
    - zetoph/kubernetes-replicator-armv6:{{ .Tag }}-go{{ .Env.GO_VERSION }}
    binaries:
      - kubernetes-replicator
    goos: linux
    goarch: arm
    goarm: '6'
  -
    dockerfile: Dockerfile
    image_templates:
    - zetoph/kubernetes-replicator-armv7:latest
    - zetoph/kubernetes-replicator-armv7:stable
    - zetoph/kubernetes-replicator-armv7:{{ .Tag }}
    - zetoph/kubernetes-replicator-armv7:{{ .Tag }}-go{{ .Env.GO_VERSION }}
    binaries:
      - kubernetes-replicator
    goos: linux
    goarch: arm
    goarm: '7'
