language: go
go:
- '1.12'
before_script:
- sudo sysctl -w net.ipv4.ip_forward=1
services:
- docker
env:
  global:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GO_VERSION=1.12
script:
- curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish --rm-dist
before_deploy:
- export FULL_IMAGE="zetoph/kubernetes-replicator"
deploy:
- provider: script
  skip_cleanup: true
  script: >-
    curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish
    --rm-dist && echo "${DOCKER_LOGIN_USERNAME}"
    && echo "${DOCKER_LOGIN_PASSWORD}" | docker login -u "${DOCKER_LOGIN_USERNAME}" --password-stdin
    && docker push "${FULL_IMAGE}:latest" && docker push "${FULL_IMAGE}-arm64:latest"
    && docker push "${FULL_IMAGE}-armv5:latest" && docker push "${FULL_IMAGE}-armv6:latest"
    && docker push "${FULL_IMAGE}-armv7:latest"
  on:
    tags: false
    branch: master
    condition: "$TRAVIS_OS_NAME = linux"
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
