language: go
go:
- '1.12'
before_script:
- sudo sysctl -w net.ipv4.ip_forward=1
services:
- docker
env:
  global:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GO_VERSION=1.12
  - secure: "O86y57aON/KrDcQc7SQOshWwDq0CcTbfYxPS885Q46ajqSK17r0I8VZHwIDzyMrIJfR+oefyI91sUWyZXOcTmm+XQi2frbe5FnWjuvh3mkuhVKRk9anlYa11dzZ37Po5rYgfDkaD4NHi4gc1sjS+TJbmVsQnDqK7b8aXfSZgNfkWWB+j39l/5imYSmy/0lIdjrJzUqZZT1Pa7Vxtevq1NXILiD6pS6yNFWrdbUxm8PRDrPnM1V0O9VbFDGrHbZuIrB7sgkNDKVmn5dNaQM9mfDebEi7E0nXGOrhrti4aR1ie1vMucPaXKjdK9oQ53yvUS7MGAX36NLg9y0USxPjqufekepyACGRuophzvaAfaASLU4Du4NO4bjyPBPtN0TX9yBKqL2yyUY00A2G4rjTTh3GJWNPJdXwow2PdsM3Di+Rf9FXirQg4/esFAUyQcS0MvJbE1TEotO3HYKdl+eGS/jLR/+9OV0kvLC0u+mZOr/H36ChaR/x/bCxEo/EphVYhoSJ+gnV6pKgpjd1/37WPQQ1FTk74PTHdu9u1ikq/azWRFzH9+vtSxK5ZWZyd6DWoMP3FXo1AFtGSZxGt7ZnU56zhk0qazuaw3vU/R5eS5ickgeTF8NkJ5BppBMJ4nsLNFxOblyrS6M3xFjduD6SNLmHOalb1R5CsIeNkOXwQ1/8="
  - secure: "YGOptbKGI/V9ckPD9um2uUjoBAqVtiLBY672UBnsGWsrxrPtDPX+saTSSprDyz54pfeGbs7kQl/cpyImu2qOWKecFNIQA3+uUtZkBgkMVpGkckql/U09UKPqeVnyyDhv/4cF6EHmF/iKnKpQuU2iHXP7w6VbwxMLCioS0I4DjjtVVA4rlMl/99tZy7idYDFOMzznab0U9EdkoxU1GMMUGcXWE7ZN+kYV62ytsXykwsQRDU0xijuSuXPHigJgN8lPq0qU0JMeZnlyUWd08eYzOJvhTF/0RhJ5PYt20QY2uKhyYZV5LmDLVyFaBN9MFn56Bphds33L2Z7G1ukR40UWqc4ZgQgE1LH9aYyAkKkJlzZd5BnFcFNv909Dn2ZvXKxJ7xgC5js6Wof7ZtDCXitwuTZwd8RQgUce8SgFncKOzuBU5PdmnPKe8xPPChdo48pCeqnExNM3KCjTIZ8HMRU+1cfy00EFW7ZPBkZu9k7t1syXIGEjnIj4YCJGjUkSKAY4Uj/T2VLuxBemkPQV+HerN97gXV1lo8XpXRTxlOf/i7gXoglTHKTRzZ6peLs0MJrB+1nqnJ7CVUfeGSPy9p8yFET6V//x3qZDz6M+Zu+aw0ooCtE/i9GbXSUYZwLhQ6t8n+BaQvnDacomieRm/0wUjmcYu4Nl1lq3MPNUcaoTtWU="
script:
- curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish --rm-dist
before_deploy:
- export FULL_IMAGE="zetoph/kubernetes-replicator"
deploy:
- provider: script
  skip_cleanup: true
  script: |
    curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish \
    --rm-dist && echo "${DOCKER_LOGIN_PASSWORD}" | docker login -u "${DOCKER_LOGIN_USERNAME}" --password-stdin \
    && docker push "${FULL_IMAGE}:latest" && docker push "${FULL_IMAGE}-arm64:latest" \
    && docker push "${FULL_IMAGE}-armv5:latest" && docker push "${FULL_IMAGE}-armv6:latest" \
    && docker push "${FULL_IMAGE}-armv7:latest"
  on:
    tags: false
    branch: master
    condition: "$TRAVIS_OS_NAME = linux"
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
