language: go
go:
- '1.12'
before_script:
- sudo sysctl -w net.ipv4.ip_forward=1
services:
- docker
env:
  global:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GO_VERSION=1.12
  - secure: MQi1FzYAh0wlRVlTORQA7EyQlTLUqYUkovh+LKjMqcHlpk9EqLgg8A+kpPgM/Ngsy1Q94kImwaKTjqCcPF15k+R3++FoNYKhbLYjH1SfO+4DfHv8Dtq/VuAVTbRc7FqURcG8QaAeStpKIFOMAAo6h3OXN3cXBxk7bHn+8l1s+33IYq598VlRjld3tG+kAM+SnKcbl4jal39eR22VxkXKH9bFp+37CjoHF7/IaIniVO16ZQXR/7X9WciDYE22tOvWxHTtL5HR4FSPTYEbc3He8B9gg6qxmwlHSmXjwx1nyFE3vZtQzxZHlAEBPdlVXPHcAUB8NjyxJfOwHNiu29NEmfs9uv0vQLQR2i0UPpe6I1MSDWG3etqfCUPAfirs01zuxDe5sALe1UlngtI8IntHIUGmIpKRgNp0H0Ue+7LgeclqR6+4vkkrdGYv9km4boFdARyCZJt6TwQSpp8BpQ/bPLevnW5Ad90eHQeklv6Q+jC1OI7xFURCYznHlrYPFUTq67Mk+js/Mr3NX0skkS8EYA0F9GqDtYDId8ADHA+pzzatbPdCNcfeR0ywHCc1SLIcAlxfttXsv1dd2FSB7wClRH4RHrkWD1Jq50Ag6eSHrG45ZKKh+1m5ZLjnNHt9Xncy/WfM0n15EEBcWh9+wjptT5XJvCIuHjwe/huYvxL/iw0=
  - secure: CiNym/ism/CWAel5TtzlB1lMesdIkh5E0BVor1I2iF4Jte8X82mNPwvmxPNy1nhFrYI/WWb0L6PIhL+zonX5XlA7IdmK8jqGdy6b+MKicD38qqs8z7K2cfcq00/iJGnIpQxGbWvLofywgSIEPPxd4WhDnWcuBm5q2G4MlNLHBz/EQwIFtWYy9+18dpuY3DDJAoyqEDl/bxFyS1da4V+hqMUBk5ZvxQ9BuN2nedU894Lba4HdGC1hrXaeTCgyvFtBigQSzCfg3B9Y8Xjw9E+CNRlJQgp8DvRYWysY12+4UWna/Pee68ono2kCikbV/psSoFZUbXjYhR0sVrwl6w73HA/fHocBKwPZpxUd5i8FzsSnewZWRjyqaXtmpVnfk4bq5d2IqRkS5ojyNMynuWDfi/i06bbsQ9tkBU2fDP1BCjpMeuPo1FZKmDVs9Xh/blDrknINYxLAuAU121JkXDS7Sfq9TBRhSM7gQdy4XJxRBSzyiyhuahuMaRi+vNEBDe/aBsBdStEgwa7Za/p3lUtRKAEtPwkE0TPks1I3/Mw+4f/HI8/KKbme9WtB914qmk9oyroge65D3Ks/XGIs6nTJP138efUloVr+G22MvcWTv2ZnYVp/dcsaLobBJw/0n7xXOM3RsvCT/jL1f+M935iwWw280cz9mJY8iyChXfwKipo=
  - secure: PgER3Rmg9hQaN6lfy+gOjyVgyEIA9UpvL20f/ieaFFju1y361RBYc2egGc9eXb7v8H6Va9Ba2lZ07QeR3vG7XKfwMQXnE0e2DLkLOhUk04P7rufQOBeGFtWdLlK5B919fB92xUrA8X5Xjj5VsmiFR0bURF4W3/WW+qPdQeubd+mocyVYyBzsb/bHhEZzv3VEkiwxfAJJQ10pRWUdHG1O7qXkgT8sQYYWDtdLMKwsZdgIguayy8zK/YNB3fW3EPNboY3cpmRkd3qq1TAIZMequVpLOHfYHCy55oEPf6KECNGvZsKtEFRddQnD5aoAkc86Ikxd2jqMGsxSwYM+kXVy8Kud8f5PukBZRs1KTvOFOKk45yMYQhhjXkTYrChviffVpXgLjBuTgwouUOvbdh3Q2wfZ3vbBRZaivJ8KlHSlKYKGiPsUUqYr+Zyr82sNl9uw4vV7jIm2IAdCxgwIDbmOnPVrlH/os01CMlqMG4sPERvgT2vI8ZxyXRmZG5No1YrmBOBS/sErdjc4nzeCtGNHc17UbSKLTTB715/Wv9xQmzk935HWccjvI3+/Df11ywqT/H8fKFSvweVxH8BsJ3d6pZZ94pBqTPyMZjZ03ESY/TwycIIvWEMxgOpKk2EhKn0zHPzxxIGSjCm43r/hjpd/mxIMeZEw+6pPBMflUg/Y7Jo=
script:
- curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish --rm-dist
before_deploy:
- if [[ -n "${DOCKER_LOGIN_USERNAME}" ]] && [[ -n "${DOCKER_LOGIN_PASSWORD}" ]] &&
  [[ -n "${DOCKER_LOGIN_URL}" ]]; then docker login -u "${DOCKER_LOGIN_USERNAME}"
  -p "${DOCKER_LOGIN_PASSWORD}" "${DOCKER_LOGIN_URL}"; fi
- export FULL_IMAGE="${DOCKER_LOGIN_URL}/${DOCKER_LOGIN_USERNAME}/kubernetes-replicator"
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish
    --rm-dist && docker push "${FULL_IMAGE}:latest" && docker push "${FULL_IMAGE}-arm64:latest"
    && docker push "${FULL_IMAGE}-armv5:latest" && docker push "${FULL_IMAGE}-armv6:latest"
    && docker push "${FULL_IMAGE}-armv7:latest"
  on:
    tags: false
    branch: master
    condition: "$TRAVIS_OS_NAME = linux"
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
