language: go
go:
- '1.12'
before_script:
- sudo sysctl -w net.ipv4.ip_forward=1
services:
- docker
env:
  global:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GO_VERSION=1.12
  - secure: "BVX1kOzYuscuV8VQIOGWV02lXmEhzX0uoXUgb1XuGIwPkYAPqyw92bWA8QSBp6HAvkONQ4j+WZ7RzByF5cDQfVlB9PmqrLJjiajE0jEmKNEloSozz7piov85r+EaiqLscScEd0NmHquvFsg/deLE/G+l3vb7mXJ8eSqgh+yLVYdkHiwqtXwbIL7o/S2IL5OORPOaFbcvGx49mkCaJgBnn58OkGy0G3MClz0Oday4yyUF/+6QGZMDWTrwhMdJn4AcLW1zgN73lGwIBo1X+i75XvPwkofNlH77QxxOAyVVqvi1gJYf5Vinm7LaaiiICXiszXrkSt3RihdzeL7nAcGGPvKOPVjqI7fCVY8KX2IEnn68Wm37MM4itOOFg02q3qrBlp8GeXmPc1oTJIAFqT3oUgdyr3eCQ0RWthwSkN8BwXefySJDq/y+wusTiJDT6MRmtA+H8nmKhTLQxjPg1jcuilzWOudUsY7BRrvtBPcAl6fsokYKXqV+WcruwKFoYdrhHf5yheCKcYDMaxb3UeD/QV/n8tf5OElc30w6NISQxWAyAJwLpwB5Xi6REAPGhFkS+AP9wrpGv6hiDXSjB3pO3dEQDJU5zMWMBdd9X19+GA9Dm/uqUEDTb70nErNkTtH78eN86CrBdCdqsFmiuJ3TqcF/0H0bsDCwuTa3ZNbD8/Q="
  - secure: "BBuVkC0wTsqbc0x4quBDy9MJO6flRNRlFjlDiJTZft9vJk/Pu6luQ+y7QQmnEqbW70ghuZIc3EE+yWRVzfS8T994lszGrxIg7sgNwXniJI8ertI130gJpJAU7XG0mBOMZ/Kv2bfSdr6G68/MN1ddpo6IqOOF437ZP+5TRnTvT2ACKNBQJ3V4rINCKQ3uKpOinUH/MYjJmILY0tke1n7bPp9a4Vm5XGjynhhlw0c5h6pBXSTih6wO13DOdJtf92F3CQI/CmPd/ecOXABBA0wbX2PNoGGiaXHHPHaupZ/UnfWDjQKVhxpTte76VV3lMbnUkHkqLcEIm2kIww2HXuya+mMOc3S7sadAxC8Regqm0qSA1l4GUT9ddbwkl8Dz4tIUeSehXsfZL1pBqOygfuMS93zTsAxhKvJLZO93Qlzkl9RpX3T0oh2N1eJGM7+yD40NDnBsiMcwC6tik9yAViMPtyKugYJmXNcr8Fd3DkMsYGsA0+nC1EfWvGdKgilX1z/KR1eri1GhV9eqSkf1A8EPCFwKDH3SPE7u9QpuQaWy6ssbWs/xfnh/TX4jfSRioxedomNoDa087noSPtrO5LrWWCq6fHEfssV8EMPFirW2aIMc7CsynIS9DP14k47TMG8kkvx4SqXZkK8vxuxbybqhWmIvwPW6u111trsnqxLx4GA="
script:
- curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish --rm-dist
before_deploy:
- if [[ -n "${DOCKER_LOGIN_USERNAME}" ]] && [[ -n "${DOCKER_LOGIN_PASSWORD}" ]]; then echo "${DOCKER_LOGIN_PASSWORD}" | docker login -u "${DOCKER_LOGIN_USERNAME}" --password-stdin; fi
- export FULL_IMAGE="${DOCKER_LOGIN_USERNAME}/kubernetes-replicator"
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish
    --rm-dist && docker push "${FULL_IMAGE}:latest" && docker push "${FULL_IMAGE}-arm64:latest"
    && docker push "${FULL_IMAGE}-armv5:latest" && docker push "${FULL_IMAGE}-armv6:latest"
    && docker push "${FULL_IMAGE}-armv7:latest"
  on:
    tags: false
    branch: master
    condition: "$TRAVIS_OS_NAME = linux"
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
